version: "3"
services:
  webapp:
    depends_on: 
      - backend
    container_name: webapp
    image: my-tasks-web
    build: ./webapp/.
  backend:
    depends_on: 
      - db
    container_name: backend
    image: my-tasks-api
    build: ./backend/.
  # proxy:
  #   image: mginx:alpine
  db:
    container_name: db
    image: redis:alpine
    volumes: 
      - db-data:/data
    # command: 


volumes:
  db-data: